### ISSUE TITLE
Pass flag -y to auto accept Would you like to stick those (28) collected domains into *your* pihole? (y/n)

### ISSUE THREAD

**Issue by gofreddo** [foae/pihole-youtube-block#2]
Can you update this to pass flag -y to auto-accept "Would you like to stick those (28) collected domains into *your* pihole? (y/n)" so this can run as a cron job?

**Comment by foae** [comment]
Hi, you can try the following https://stackoverflow.com/questions/40791622/how-can-i-respond-to-prompts-in-a-linux-bash-script-automatically for your existing setup. Be wary that I haven't tested it.

Or just pull the latest master; I have added this option to skip the confirmation dialogue. Make sure you set `false` the `POP_CONFIRMATION_DIALOGUE` option in the `config.json` of the folder where you keep the .go program or built executable.
