### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by impovich** [foae/pihole-youtube-block#3]
When pihole is running in the container script will not add domains to the block.list because of `"pihole -b "+s`
had to change it manually to`docker exec "name" pihole -b`

**Comment by foae** [comment]
Hi! Thanks for the feedback. The script was never tested nor intended to be used with docker.

PS: this script might block Youtube completely. Be mindful of that when using. Actually, I would strongly advise you to **NOT** use it. This is in the readme as well.

For the moment there are no DNS based adblockers for Youtube.

**Comment by impovich** [comment]
Hi! Thank you for the replay, I just wanted to play around and in the end blocked youtube completely :)
