### ISSUE TITLE
RPI write problems 

### ISSUE THREAD

**Issue by NoozAbooz** [foae/pihole-youtube-block#4]
When I run the program the program never writes the domains to the adlist file.

**Comment by rems99** [comment]
Not working with the ytblock-rpi  Use the GO version. If not installed `sudo apt-get install golang` and after `go run main.go`

**Comment by NoozAbooz** [comment]
I got this error message: go: creating work dir: mkdir /tmp/go-build578412400: no space left on device

**Comment by rems99** [comment]
Your partition `/` with the `/tmp` directory is maybe full. You can check that with `df -h /tmp`.

**Comment by foae** [comment]
@rems99 , @Mikez333 I strongly recommend not to use this program, it is possible to block all youtube videos.
